-- Update settings table to ensure all required fields exist
-- This script will add missing columns if they don't exist

-- Add zalo column if it doesn't exist
ALTER TABLE cai_dat_website 
ADD COLUMN IF NOT EXISTS zalo VARCHAR(20) DEFAULT NULL;

-- Ensure all required columns exist with proper defaults
ALTER TABLE cai_dat_website 
ADD COLUMN IF NOT EXISTS ten_website VARCHAR(255) NOT NULL DEFAULT 'Orianna Shop',
ADD COLUMN IF NOT EXISTS mo_ta_website TEXT,
ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS favicon_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS dia_chi TEXT,
ADD COLUMN IF NOT EXISTS so_dien_thoai VARCHAR(20),
ADD COLUMN IF NOT EXISTS email VARCHAR(100),
ADD COLUMN IF NOT EXISTS hotline VARCHAR(20),
ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS youtube_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS tiktok_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS ten_cong_ty VARCHAR(255),
ADD COLUMN IF NOT EXISTS ma_so_thue VARCHAR(50),
ADD COLUMN IF NOT EXISTS giay_phep_kinh_doanh VARCHAR(100),
ADD COLUMN IF NOT EXISTS chinh_sach_bao_hanh TEXT,
ADD COLUMN IF NOT EXISTS chinh_sach_doi_tra TEXT,
ADD COLUMN IF NOT EXISTS chinh_sach_giao_hang TEXT,
ADD COLUMN IF NOT EXISTS chinh_sach_bao_mat TEXT,
ADD COLUMN IF NOT EXISTS tinh_nang_1_icon VARCHAR(10),
ADD COLUMN IF NOT EXISTS tinh_nang_1_tieu_de VARCHAR(100),
ADD COLUMN IF NOT EXISTS tinh_nang_1_mo_ta TEXT,
ADD COLUMN IF NOT EXISTS tinh_nang_2_icon VARCHAR(10),
ADD COLUMN IF NOT EXISTS tinh_nang_2_tieu_de VARCHAR(100),
ADD COLUMN IF NOT EXISTS tinh_nang_2_mo_ta TEXT,
ADD COLUMN IF NOT EXISTS tinh_nang_3_icon VARCHAR(10),
ADD COLUMN IF NOT EXISTS tinh_nang_3_tieu_de VARCHAR(100),
ADD COLUMN IF NOT EXISTS tinh_nang_3_mo_ta TEXT,
ADD COLUMN IF NOT EXISTS tinh_nang_4_icon VARCHAR(10),
ADD COLUMN IF NOT EXISTS tinh_nang_4_tieu_de VARCHAR(100),
ADD COLUMN IF NOT EXISTS tinh_nang_4_mo_ta TEXT,
ADD COLUMN IF NOT EXISTS meta_title VARCHAR(255),
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS meta_keywords TEXT,
ADD COLUMN IF NOT EXISTS gio_lam_viec TEXT,
ADD COLUMN IF NOT EXISTS phi_ship_toi_thieu DECIMAL(10,2) DEFAULT 25000,
ADD COLUMN IF NOT EXISTS tien_te VARCHAR(10) DEFAULT 'VND',
ADD COLUMN IF NOT EXISTS ngon_ngu VARCHAR(10) DEFAULT 'vi',
ADD COLUMN IF NOT EXISTS ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Insert default data if table is empty
INSERT IGNORE INTO cai_dat_website (
    cai_dat_id,
    ten_website, 
    mo_ta_website, 
    dia_chi, 
    so_dien_thoai, 
    email, 
    hotline,
    ten_cong_ty, 
    ma_so_thue, 
    giay_phep_kinh_doanh,
    facebook_url, 
    instagram_url, 
    zalo,
    chinh_sach_bao_hanh, 
    chinh_sach_doi_tra, 
    chinh_sach_giao_hang, 
    chinh_sach_bao_mat,
    tinh_nang_1_icon, tinh_nang_1_tieu_de, tinh_nang_1_mo_ta,
    tinh_nang_2_icon, tinh_nang_2_tieu_de, tinh_nang_2_mo_ta,
    tinh_nang_3_icon, tinh_nang_3_tieu_de, tinh_nang_3_mo_ta,
    tinh_nang_4_icon, tinh_nang_4_tieu_de, tinh_nang_4_mo_ta,
    meta_title, 
    meta_description, 
    gio_lam_viec, 
    phi_ship_toi_thieu
) VALUES (
    1,
    'Orianna Perfume Store',
    'Cửa hàng nước hoa chính hãng uy tín',
    '43 Nguyễn Chí Thanh, Trà Vinh\ntỉnh Vĩnh Long, Việt Nam',
    '091 123 4567',
    'orianna@gmail.com',
    '1900 xxxx',
    'Cửa hàng nước hoa Orianna',
    '0123456789',
    'Đang cập nhật',
    'https://facebook.com/orianna.perfume.vinhlong',
    'https://instagram.com/orianna_perfume_vl',
    '091 123 4567',
    'Sản phẩm nước hoa chính hãng được bảo hành về chất lượng. Đổi trả nếu phát hiện hàng giả hoặc không đúng mô tả.',
    'Đổi trả sản phẩm trong 3 ngày nếu sản phẩm bị lỗi hoặc không đúng mô tả. Sản phẩm phải còn nguyên seal.',
    'Giao hàng tận nơi trong khu vực Vĩnh Long. Phí ship 25,000 VND. Miễn phí ship cho đơn hàng từ 500,000 VND.',
    'Cam kết bảo mật thông tin cá nhân của khách hàng. Không chia sẻ thông tin cho bên thứ ba khi chưa có sự đồng ý.',
    '🚚', 'Giao hàng tận nơi', 'Giao hàng tận nơi trong khu vực Vĩnh Long',
    '💯', 'Nước hoa chính hãng', '100% nước hoa chính hãng từ các thương hiệu uy tín',
    '👨‍💼', 'Tư vấn chuyên nghiệp', 'Đội ngũ tư vấn am hiểu về nước hoa',
    '💰', 'Giá cả hợp lý', 'Giá cả cạnh tranh, nhiều ưu đãi hấp dẫn',
    'Orianna Perfume Store - Nước hoa chính hãng',
    'Orianna Shop chuyên cung cấp nước hoa chính hãng từ các thương hiệu nổi tiếng với giá tốt nhất',
    'Thứ 2 - Thứ 6: 8:00 - 20:00\nThứ 7 - CN: 9:00 - 18:00',
    25000
);